version: '3.2'

networks:
  cig_nginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - {subnet: "172.18.0.0/16"}


services:
  collectdserver.docker:
    container_name: reponame_collectdserver_dev
    build:
      context: .
      dockerfile: Collectd-Dockerfile
      args:
        - buildenv=development
        - monitoring_user=admin
        - monitoring_pass=test1234
        - serial_num=DEVICE-UNIQUE-ID
    image: reponame_collectdserver:dev
    privileged: true
    networks:
      - cig_nginx
    command: ["collectd", "-C", "/etc/collectd.conf", "-f"]


  grafana.docker:
    image: grafana/grafana:latest
    container_name: reponame_grafana_dev
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - cig_nginx


  nginx.docker:
    container_name: reponame_nginx_dev
    build:
      context: .
      dockerfile: Nginx-Dockerfile
      args:
        - buildenv=development
    ports:
      - 80:80
      - 443:443
      - "25255:25255/udp"
    image: reponame_nginx:dev
    volumes:
      - ~/Workspace/server:/usr/share/nginx/html
    extra_hosts:
      - "cloud_backend:192.168.178.34"
    networks:
      - cig_nginx


  influxdb.docker:
    container_name: reponame_influxdb_dev
    build:
      context: .
      dockerfile: InfluxDB-Dockerfile
      args:
        - buildenv=development
    image: reponame_influxdb:dev
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - type: bind
        source: $PWD/data
        target: /var/lib/influxdb/data
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=mydb
      - INFLUXDB_USER=testuser
      - INFLUXDB_USER_PASSWORD=test1234
      - INFLUXDB_REPORTING_DISABLED=false
    networks:
      - cig_nginx
