version: '3.2'

volumes:
  typesdb:


services:
  base_collectd:
    container_name: reponame_base_collectd_dev
    build:
      context: .
      dockerfile: Collectd-Dockerfile
      args:
        - buildenv=development
        - influxdb_host=influxdb
    image: reponame_base:dev
    ports:
      - "25826:25826/udp"
    privileged: true
    volumes:
      - type: volume
        source: typesdb
        target: /usr/share/collectd


  grafana:
    image: grafana/grafana:latest
    container_name: reponame_grafana_dev
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - influxdb
    links:
      - influxdb


  influxdb:
    container_name: reponame_influxdb_dev
    build:
      context: .
      dockerfile: InfluxDB-Dockerfile
      args:
        - buildenv=development
        - influxdb_host=influxdb
    image: reponame_influxdb:dev
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    volumes:
      - type: bind
        source: $PWD/data
        target: /var/lib/influxdb/data
      - type: volume
        source: typesdb
        target: /usr/share/collectd
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=influxdb_test
      - INFLUXDB_USER=influxdb_test
      - INFLUXDB_USER_PASSWORD=test123
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    depends_on:
      - base_collectd
    links:
      - base_collectd
